### ISSUE TITLE
Need a Gernerates pick and place files

### ISSUE THREAD

**Issue by jasinghuang** [bdring/Grbl_ESP32_Development_Controller#1]
Hello! I'm going to make your version of control borad(https://github.com/bdring/Grbl_ESP32_Development_Controller) to replace my old uno control board, I am trying to make a pcb with SMT,and the seller need ’**Gernerates pick and place files**‘, and I can not find it in the zip.

Thank you!

**Comment by bdring** [comment]
I don't have a pick and place file for it. How many are you making?

**Comment by jasinghuang** [comment]
> I don't have a pick and place file for it. How many are you making?

I am making only 2 boards, one for insurance.

**Comment by tpickett** [comment]
jlpcb will do most of the work for smt if this is added. easy to order 5 of them for cheap. would love to support on Tindie though ;)

**Comment by bdring** [comment]
[Added](https://github.com/bdring/Grbl_ESP32_Development_Controller/blob/master/gerbers/V4p1/V4p1_centroid.csv)

**Comment by guestisp** [comment]
For jlbpcb , the BOM and the pick&trace file has to be modified. In example, in the BOM, some components are missing the description end even the columns title and positioning is not good for jlbpcb
