### ISSUE TITLE
Driving MOSFETs directly with the TXS0101

### ISSUE THREAD

**Issue by shreeramlive** [bdring/Grbl_ESP32_Development_Controller#2]
According to the output of the **TXS0101** IC, the max output current is rated as **100mA**.
_[ Continuous current through VCCA, VCCB, or GND = ±100 mA ]_
So can we drive a **MOSFET** or light up up a **few LED**s directly from the output of level shifter?
Would this cause any **damage** to the **ESP32** board?
Would there be better protection to the board if all the **outputs** are routed through voltage shifters (something like TXS0104 for more pins) ?

![Screenshot from 2019-11-06 10-10-51](https://user-images.githubusercontent.com/42814228/68269101-8aa26800-007e-11ea-9f44-76c5819ba9a0.png)

And one more doubt, what happens when a pin ( configured as **output** ) gets **shorted with ground**? Like connecting a **limit switch** wrongly a to pin which is mapped for **Spindle output**.

**Comment by bdring** [comment]
The TXS0101 can switch current to gnd. It uses a 10k pullup for 5v.  You could drive some LEDs by connecting the low side of the LED. You can't drive much with the 5v signal.

**Comment by shreeramlive** [comment]
Thanks for the info @bdring
