### ISSUE TITLE
the 4.1 card is blocked in USPS facility

### ISSUE THREAD

**Issue by Filcanna** [bdring/Grbl_ESP32_Development_Controller#4]
I cannot experiment on this card, because I'm waiting delivery and it seems it's stuck in USA (from may 26). 
I understand Covid19 emergency, but customer care appears lower than standard.. 
No one seems to be caring about my questions. 
For bdring: feel free to erase this issue I raised

**Comment by bdring** [comment]
Unfortunately shipments are taking as long as 8 weeks during this pandemic. It is outside of my control. So far all packages have arrived eventually.

How would you like me to handle this case? The only 2 realistic options are to refund your purchase or resend with an expedited delivery.

**Comment by Filcanna** [comment]
Well
I’d like to put my hands on the card..ok I’ll wait some more days...Thanks in advance 
FC
